### ISSUE TITLE
Comments/ input on section: EBM Helpt Organisaties in een Complexe Wereld om Empirisme te Gebruiken in de Zoektocht naar hun Doelen

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#5]
Input on the translation in the section below "EBM Helpt Organisaties in een Complexe Wereld om Empirisme te Gebruiken in de Zoektocht naar hun Doelen"

1. One small typo in the word Tussenliggend (has an extra 'd'):
_Tussenliggende Doelen, waarvan het behalen aangeeft dat de organisatie op weg is naar het Strategisch Doel. De weg naar het Tussen**d**liggende Doel is vaak nog steeds enigszins onzeker, maar niet volledig onbekend._

2. 

![image](https://user-images.githubusercontent.com/52327049/104180760-95d0f080-5405-11eb-9429-220b1edc8cd5.png)

In Inspect: should 'Based on your measures, what did you learn' be translated in past time instead? At the moment it says: 'Wat leren we van de metingen?'. Would it be better to say: 'wat hebben we van de metingen geleerd?'

In Adaptation, it says 'What might you try next', which is currently translated in 'Wat kunnen we nu proberen'. I actually like the non literal translation of this, using the word 'nu' instead and 'kunnen'. If I would translate it more literally I probably would have used something like' Wat is het volgende dat we zouden kunnen uitproberen?' Not sure if it makes a difference but maybe some food for thought :-)

**Comment by sjoerdly** [comment]
typo fixed, good catch.

For 2. I will think about it, and will have to wait until I am at a decent pc to fix the image text, as it seems the SVG is not properly editable on my SVG iPad apps.

I will adopt the first suggestion (past tense).

For the second one, I took the liberty to modify the translation because I like that better too. As long as we feel that it still fits what is meant in the original version, but fits better according to us (and in Dutch) that is most important. (Rank intent, impact & meaning over exact translation)

Thanks for the input @glaudia !

**Comment by sjoerdly** [comment]
Fixed suggestion for inspecteren now too. I will let aanpassen stay in my own more liberal interpretation. I just like it too much.
